name: ProxmoxSDK Push Changes to App Repo

on:
  push:
    branches:
      - main

env:
  APP_REPO: HavelCTF/app
  SOURCE_REPO: ${{ github.repository }}
  SUBTREE_PREFIX: ${{ github.event.repository.name }}

jobs:
  push-app:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Setup Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Clone the app repository
        run: |
          git clone https://neo-jgrec:${{ secrets.APP_GITHUB_PAT_TOKEN }}@github.com/${{ env.APP_REPO }}.git _app

      - name: Pull/Add app repository as a subtree
        working-directory: _app
        run: |
          REMOTE_URL="https://neo-jgrec:${{ secrets.APP_GITHUB_PAT_TOKEN }}@github.com/${{ env.SOURCE_REPO }}.git"
          if [ -d "${{ env.SUBTREE_PREFIX }}" ]; then
            git subtree pull --prefix=${{ env.SUBTREE_PREFIX }} "$REMOTE_URL" main --squash
          else
            git subtree add --prefix=${{ env.SUBTREE_PREFIX }} "$REMOTE_URL" main --squash
          fi

      - name: Push to app repository
        working-directory: _app
        run: |
          git push origin main
